### ISSUE TITLE
Canvas doesn't work properly on Firefox / Android

### ISSUE THREAD

**Issue by dolmen** [replicate/scribble-diffusion#17] opened 2023-02-18 18:44 UTC
I tried https://scribblediffusion.com/ on multiple devices (phone, tablet) with Mozilla Firefox, and drawing doesn't work properly:
* the initial image is not fully rendered: it looks like the image is randomly cropped on the right and on the bottom
* when drawing on a touch screen drawing doesn't follow the finger correctly. Well, sometimes it works, sometimes not.

**Comment by zeke** [comment] 2023-02-19 07:04
Thanks for reporting.

Related #15

**Comment by pascalchevrel** [comment] 2023-02-20 11:02
Hi,

If this result into being a Firefox bug in our canvas implementation, I would be happy to know more about it and see if we can get this fixed rapidly, don't hesitate to ping me if this is the case.

Regards
Pascal Chevrel
Firefox Release Manager

**Comment by zeke** [comment] 2023-02-20 19:59
Thanks @pascalchevrel 

>  initial image is not fully rendered: it looks like the image is randomly cropped on the right and on the bottom

☝🏼 This part is definitely not a Firefox issue. See #15

Not sure about the touch screen drawing though.

**Comment by MrMarble** [comment] 2023-02-23 10:20
Hi! I don't think is a Firefox issue, I made this simple app a long time ago and is working fine on Firefox: https://draw-app.vercel.app (a sketch drawing example from scratch). It may be related to this issue https://github.com/vinothpandian/react-sketch-canvas/issues/114

If you're open to contributions, I may have a look at it later

**Comment by zeke** [comment] 2023-02-28 21:20
Yeah this is the issue: https://github.com/vinothpandian/react-sketch-canvas/issues/54

The issue is marked as closed but I don't think it's actually fixed in the latest release of `react-sketch-canvas`:

https://www.loom.com/share/b804e56441d6494f96d24e83dd2634ed

**Comment by softyoda** [comment] 2023-03-01 11:53
I have the same issue on firefox on windows and firefox for android. It's almost all white, and sometimes it displays half of the canvas 
![image](https://user-images.githubusercontent.com/13988751/222132125-402c8ed6-9a10-4aa3-b3ea-ea813b45b075.png)

**Comment by zeke** [comment] 2023-04-13 16:21
I think this was fixed by https://github.com/replicate/scribble-diffusion/issues/31

**Closed by zeke** 2023-04-13 16:21 UTC
